name: React & DotNet Core CI

on: [push]

env:
  DOTNET_VERSION: '8.0.0' # The .NET SDK version to use

jobs:
  build_spa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build, and test
        run: |
          cd my-app
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build Spa
          path: |
            my-app/build
  publish_api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        cd my-api
        dotnet restore
      
    - name: Build
      run: |
        cd my-api
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../dotnet-webapp -r linux-x64 --self-contained true /p:UseAppHost=true
      
    - uses: actions/upload-artifact@v4
      name: Archive api artifacts
      with:
        name: build Api
        path: |
          my-api/bin/Release/net8.0/publish